# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Security Assignments | AY 20
email: dave@daveeargle.com
description: >- # this means to ignore newlines until "baseurl:"
  Security labs for a university course, "Information Security Management."
  Archived from academic year 20-21.
  Authors Dave Eargle and Anthony Vance
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://daveeargle.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: deargle
github_username:  deargle
repository: 'deargle/security-assignments-ay20'

instructorcollab_username: deargle
instructorcollab_domain: colorado.edu

remote_theme: deargle/security-assignments-theme
#theme: security-assignments-theme

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - script/
  - assets/vendor/jquery/src
  - assets/vendor/bootstrap-sass/assets/fonts
  - assets/vendor/bootstrap-sass/assets/stylesheets
  - assets/vendor/bootstrap-sass/assets/javascripts/bootstrap/
  - README.md

host: 0.0.0.0

# Collections
collections:
    labs:
        output: true
    activities:
        output: true
    tutorials:
        output: true
    projects:
        output: true
    books:
    films:
    readings:

defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "labs"
        values:
            layout: assignment
    -
        scope:
            path: ""
            type: "activities"
        values:
            layout: assignment
